# Generated by Django 4.0.6 on 2022-11-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('img', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
